[FEAT] 계좌 조회
woorifisa-projects-3rd/WeKids-BE pull request #26
Opened 2024-11-11 07:37 UTC by jabin1221

# 📄 Work Description
- 계좌 조회 API

# ⚙️ ISSUE
- closed #5 

# 📷 Screenshot
 - 테스트
![image](https://github.com/user-attachments/assets/f6a36751-8373-4713-9381-df91498656ae)
 - 포스트맨
![image](https://github.com/user-attachments/assets/efe124a6-aec5-46f8-a964-55f67c09d356)

# 💬 To Reviewers
코드 리뷰 부탁드립니다!

2024-11-13 11:30 UTC, cbj0010 reviewed
고생하셨스용~

2024-11-13 11:30 UTC, cbj0010 commented on src/main/java/com/wekids/backend/account/controller/AccountController.java
> +    }
이거 /api/vi~ 이 공통 부분도 저 위에 RequestMapping으로 빼서 쓰는건 어떠신가용?

2024-11-13 11:30 UTC, cbj0010 commented on src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
> +                .orElseThrow(() -> new WekidsException(ErrorCode.ACCOUNT_NOT_FOUND, "계좌를 찾을 수 없습니다."));
저도 잘 모르기는 한데.이 "계좌를 찾을 수 없습니다." 보다는 어떤 이유로 계좌를 찾을 수 없는지를 적는게 맞을 거 같아요!
예를 들면 account_id의 변수값을 확인한다던지용!

2024-11-15 00:07 UTC, cbj0010 commented on src/main/java/com/wekids/backend/account/controller/AccountController.java
> +    @GetMapping("/api/v1/accounts")
저희 api가 다 공통적으로 "/api/v1/"이 들어가는데 이것도 공통으로 뺴놓고 쓰면 좋을 것 같습니다!

2024-11-15 00:07 UTC, cbj0010 commented on src/main/java/com/wekids/backend/account/dto/response/AccountResponse.java
>      private String account_number;
이것만 스네이크 케이스로 쓰신 이유가 있을까용?

2024-11-15 00:07 UTC, cbj0010 commented on src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
> +        ).collect(Collectors.toList());
요거는 따로 예외처리는 이제 안해주시는건가용?

2024-11-15 02:04 UTC, jabin1221 commented on src/main/java/com/wekids/backend/account/dto/response/AccountResponse.java
>      private String account_number;
수정하겠습니다!

2024-11-15 02:05 UTC, jabin1221 commented on src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
> +        ).collect(Collectors.toList());
findAll만 호출하는 단순한 코드라고 생각하고 놓친거 같습니다 감사합니다!

2024-11-15 12:43 UTC, dpdms529 requested changes

2024-11-15 12:43 UTC, dpdms529 commented on src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
> +                .orElseThrow(() -> new WekidsException(ErrorCode.ACCOUNT_NOT_FOUND, "계좌를 찾을 수 없습니다."));
윤정이 말이 맞아요
지금처럼 예외 메시지 보내면 "계좌를 찾을 수 없습니다."가 message랑 detail에 둘 다 들어가져요.

2024-11-15 12:43 UTC, dpdms529 commented on src/test/java/com/wekids/backend/account/repository/AccountRepositoryTest.java
> +    AccountService accountService;
Service에 대한 테스트는 ServiceTest로 따로 파일 만들어서 해주세요.
각 계층 별로 하는 역할이 다르니깐 분리해서 계층별로 역할이 잘 동작하는지 테스트해야해요.

2024-11-18 02:29 UTC, jabin1221 commented on src/test/java/com/wekids/backend/account/repository/AccountRepositoryTest.java
> +    AccountService accountService;
수정해보겠습니다 감사합니다

2024-11-19 05:07 UTC, khwoowoo requested changes

2024-11-19 05:07 UTC, khwoowoo commented on src/main/java/com/wekids/backend/account/dto/response/AccountResponse.java
> +        this.bankName = "우리은행";
확장성있게 은행이름까지 받으면 어떨까요??

2024-11-19 05:07 UTC, khwoowoo commented on src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
> +        //List<BaasAccountResponse> responseList = Arrays.asList(responseArray);
예은님이 BaaS에서 간단하게 응답만해주는 Controller 작성해준시다고 하니, 코드 작성해서 테스트하면 될 것 같습니다! 아니면 바로 임시 서버 만들어서 진행해도 좋고요!

2024-11-19 05:07 UTC, khwoowoo commented on src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
> +    }
전부 가져와서 하지말고 가지 해당 id에 있는 것만 가져오는건 어떨까요?? 그리고 id를 어디서 사용하나요?? 코드에서는 안 보이는 것 같습니다!

2024-11-19 05:07 UTC, khwoowoo commented on src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
> +    }
나중에서 BaaS서버에서 응답받는 걸로 하고 이거 지워도 될 것 같습니다

2024-11-19 07:42 UTC, jabin1221 commented on src/main/java/com/wekids/backend/account/dto/response/AccountResponse.java
> +        this.bankName = "우리은행";
수정해보겠습니다!

2024-11-19 10:58 UTC, dpdms529 commented on src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
> +    private AccountRepository accountRepository;
private final로 해주시고, @Autowired는 빼도 될 것 같습니다.

2024-11-19 10:58 UTC, dpdms529 commented on src/test/java/com/wekids/backend/account/service/AccountServiceTest.java
> +        ResponseEntity<BaasAccountResponse[]> responseEntity = new ResponseEntity<>(mockResponse, HttpStatus.OK);
이거 왜 List 안쓰고 배열 쓴건가요?

2024-11-19 10:58 UTC, dpdms529 commented on src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
> +        ResponseEntity<BaasAccountResponse[]> response = restTemplate.getForEntity(url, BaasAccountResponse[].class, uriVariables);
이거 List<BaasAccountResponse>라고 하면 안받아지나요?
그리고 문단을 좀 나누면 좋을 것 같습니다.

2024-11-19 10:58 UTC, dpdms529 commented on src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
> +        System.out.println(responseList);
print하는 코드는 빼주세요

2024-11-19 10:58 UTC, dpdms529 commented on src/main/java/com/wekids/backend/account/controller/AccountController.java
> +    private AccountService accountService;
private final로 써주시고 @Autowired는 지워주세요.

2024-11-19 10:58 UTC, dpdms529 commented on src/main/java/com/wekids/backend/account/controller/AccountController.java
> +@RequestMapping("/api/v1/accounts")
/api/v1/baas/accounts로 바꾸고 컨트롤러 따로 써야될 것 같아요.
여기서 읽어오는게 저희 DB에 있는 자원을 읽어오는게 아니라서 나중에 저희 accounts 용 메서드랑 헷갈릴거같아요

2024-11-25 00:22 UTC, khwoowoo approved these changes

2024-11-25 00:31 UTC, dpdms529 approved these changes

2024-11-25 00:32 UTC, merged