[FEAT] transaction save memo
woorifisa-projects-3rd/WeKids-BE pull request #39
Opened 2024-11-16 16:22 UTC by cbj0010

# 📄 Work Description
- 메모 저장기능 api 구현

# ⚙️ ISSUE
- closed #10 

# 📷 Screenshot
메모 저장할 Id 호출 후 반영

![image](https://github.com/user-attachments/assets/d8bc5fee-733b-4990-8284-a77a663652c4)
![image](https://github.com/user-attachments/assets/26166c6e-d618-4eed-8cfb-137efa7bab9c)
업데이트 후
![image](https://github.com/user-attachments/assets/0781fac7-d247-4e1e-970a-b236265c50d2)

# 💬 To Reviewers
리뷰어들에게 하고 싶은 말
그냥 문득 postMan 찍어보면서 든 생각인데용.. 
200일때도 responseMessage에 sucess이런게 있다면 참 조을거 같아요.. 모랄가 더 직관적이랄까..? ⭐️

2024-11-18 04:37 UTC, dpdms529 requested changes

2024-11-18 04:37 UTC, dpdms529 commented on src/main/java/com/wekids/backend/accountTransaction/controller/AccountTransactionController.java
> +        return ResponseEntity.ok().build();
204 보내면 될거같습니다.
no_content

2024-11-18 04:37 UTC, dpdms529 commented on src/main/java/com/wekids/backend/accountTransaction/dto/request/UpdateMemoRequest.java
> +    private UpdateMemoRequest(){}
생성자 어노테이션 쓰세요

2024-11-18 04:37 UTC, dpdms529 commented on src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImpl.java
> +        AccountTransaction accountTransaction = accountTransactionById(transactionId, "id값은");
"id값은"?????

2024-11-18 04:37 UTC, dpdms529 commented on src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImpl.java
> +        AccountTransaction accountTransaction = accountTransactionById(transactionId, "memod업데이트를 하는 id");
"memod업데이트를 하는 id"????????

2024-11-18 04:37 UTC, dpdms529 commented on src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImpl.java
> +    private AccountTransaction accountTransactionById(Long transactionId, String message) {
메서드명은 동사로

2024-11-18 16:41 UTC, cbj0010 commented
리뷰 반영 다 했습니당~!

2024-11-19 05:17 UTC, khwoowoo commented on src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImpl.java
> +        return accountTransaction;
바로 return 하는건 어떨까요??

2024-11-19 05:17 UTC, khwoowoo commented on src/test/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImplTest.java
> +    }
따로 때서 전역으로 하신 이유가 있을까요??

2024-11-19 05:17 UTC, khwoowoo commented on src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImpl.java
> +        accountTransactionRepository.save(accountTransaction);
이거 db에서 가져와서 변경하면 save 안 해도 될 것 같은데, 작성한 이유가 있나요?? 더티 체킹이 안 되나요??

2024-11-19 05:30 UTC, cbj0010 commented on src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImpl.java
> +        accountTransactionRepository.save(accountTransaction);
더티 체킹을 몰랐어요..!!!! 그래서 save를 작성해뒀는데 없애도록 하겠습니당~

2024-11-19 05:32 UTC, cbj0010 commented on src/test/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImplTest.java
> +    }
다른 테케에서도 어차피 넣어줘야 되는 애들이라서 전역으로 뺴고 썼습니다! 
좀 다르게 해서 보내줘야 되는 곳만 생성자 어노테이션을 써서 해줬습니다

2024-11-21 01:27 UTC, cbj0010 commented
리뷰 반영 다 했지롱!!

2024-11-21 01:33 UTC, dpdms529 approved these changes
테스트 코드 기능별로 나누면 좋을 것 같은데 일단 좋습니다.

2024-11-21 01:35 UTC, khwoowoo approved these changes

2024-11-21 01:46 UTC, merged