[FEAT] 디자인 조회/생성
woorifisa-projects-3rd/WeKids-BE pull request #40
Opened 2024-11-18 01:36 UTC by AnChanUng

# 📄 Work Description
- 디자인을 조회하고 생성하는 기능입니다.

# ⚙️ ISSUE
- closed #34 #36 

# 📷 Screenshot
 - 동영상, 사진, 로그 등등
 - ex) 큐알 성공 이미지, 스웨거, 포스트맨 등
 
 - 디자인 조회
![image](https://github.com/user-attachments/assets/e777754e-71fc-45df-a4f5-800cc76c09b1)

- 디자인 생성(저장)
![image](https://github.com/user-attachments/assets/0ba99af2-6559-40fb-8039-8c426747bc04)

 
- 디자인 조회 테스트코드
![image](https://github.com/user-attachments/assets/a84c9e8e-28db-4a3c-9d58-4843e632673d)

- 디자인 생성 테스트코드
![image](https://github.com/user-attachments/assets/88629108-2198-4285-b30e-b2642340d7ec)

# 💬 To Reviewers
리뷰 부탁드립니다!

2024-11-18 02:01 UTC, dpdms529 requested changes

2024-11-18 02:01 UTC, dpdms529 commented on src/main/java/com/wekids/backend/design/domain/Design.java
> +@Setter
Setter 쓰지 마세요

2024-11-18 02:01 UTC, dpdms529 commented on src/main/java/com/wekids/backend/design/domain/Design.java
> +@NoArgsConstructor
access 레벨 Protected로 해주세요

2024-11-18 02:01 UTC, dpdms529 commented on src/main/java/com/wekids/backend/design/service/DesignService.java
> +    DesignResponse createDesign(Long memberId, DesignCreateRequest request);
디자인 생성 API ResponseBody 없으니깐 void로 해야될거같은데요

2024-11-18 02:01 UTC, dpdms529 commented on src/main/java/com/wekids/backend/design/service/DesignServiceImpl.java
> +                .orElseThrow(() -> new WekidsException(ErrorCode.DESIGN_NOT_FOUND, "디자인을 찾을 수 없습니다."));
detail 메시지는 어느 부분에서 에러가 나는건지 쓰는겁니다.
"디자인을 찾을 수 없습니다." 같은 메시지는 ErrorCode message에 적는거구요.
ex) "memberId:" + memberId
아래도 다 수정해주세요

2024-11-18 02:01 UTC, dpdms529 commented on src/main/java/com/wekids/backend/design/service/DesignServiceImpl.java
> +    private <E extends Enum<E>> String getEnumValues(Class<E> enumClass) {
이게 어디서 쓰이고 있어요??

2024-11-18 02:01 UTC, dpdms529 commented on src/test/java/com/wekids/backend/support/fixture/DesignFixture.java
> +
Lombok Builder 사용하는 방식으로 바꿔주세요

2024-11-18 04:44 UTC, AnChanUng commented
11.18.13:44 모두 수정완료~~

2024-11-19 05:38 UTC, khwoowoo commented on src/main/java/com/wekids/backend/design/dto/result/DesignResult.java
이거 코드 사용하는데 만드신 이유가 있을까요??

2024-11-19 05:38 UTC, khwoowoo commented on src/main/java/com/wekids/backend/design/controller/DesignController.java
> +        return ResponseEntity.created(location).build();
응답할 때 주소까지 주는 이유가 있을까요?? 
그리고 준다면 id까지 보내줘야 하지않을까요??
```
return ResponseEntity
	            .created(URI.create("http://localhost:8080/api/v1/design/" +designId))
              .build();
```

굳이 안 보내도 된다면 이렇게 하는 것도 좋을 것 같습니다!
```
ResponseEntity.status(HttpStatus.CREATED).build();
```

2024-11-19 05:38 UTC, khwoowoo commented on src/main/java/com/wekids/backend/design/service/DesignServiceImpl.java
> +                .build();
생성하는 메서드 따로 만드는게 좋을 것 같습니다

2024-11-19 05:38 UTC, khwoowoo commented on src/main/java/com/wekids/backend/design/dto/request/DesignCreateRequest.java
> +    private String character;
이거 바로 enum으로 받으면 될 것 같은데 안 하신 이유가 잇나요?

2024-11-19 05:38 UTC, khwoowoo commented on src/main/java/com/wekids/backend/design/service/DesignServiceImpl.java
> +        CharacterType character = CharacterType.valueOf(request.getCharacter());
dto에서 enum으로 바로 받으면 이렇게 변환 안 해도 될 것 같습니다!

2024-11-25 01:44 UTC, khwoowoo approved these changes

2024-11-25 01:44 UTC, dpdms529 approved these changes

2024-11-25 01:44 UTC, dpdms529 commented on src/main/java/com/wekids/backend/design/controller/DesignController.java
> +        return ResponseEntity.created(location).build();
이거 URI가 만들어진 데이터를 어디서 조회할 수 있는지를 보내주는거래요.
/api/v1/design/:id
이런식으로

2024-11-25 01:44 UTC, dpdms529 commented on src/main/java/com/wekids/backend/design/service/DesignServiceImpl.java
> +        Design newDesign = Design.builder()
Design이랑 member랑 연관 관계 설정되어있는데 member 넣어줘야하는거아니예요?

2024-11-25 01:44 UTC, dpdms529 commented on src/test/java/com/wekids/backend/design/service/DesignServiceImplTest.java
> +    private static final Logger log = LoggerFactory.getLogger(DesignServiceImplTest.class);
@Slf4j 쓰면 되지 않나요?

2024-11-25 01:44 UTC, merged