[FEAT] 부모 계정 조회
woorifisa-projects-3rd/WeKids-BE pull request #42
Opened 2024-11-18 02:14 UTC by jabin1221

# 📄 Work Description
- 부모 계정 조회

# ⚙️ ISSUE
- closed #15 

# 📷 Screenshot
 - 포스트맨
![image](https://github.com/user-attachments/assets/29421413-a526-44c0-b8dc-ebe97fe5935e)
 - 테스트코드(성공)
![image](https://github.com/user-attachments/assets/47b22c63-5c25-4e48-b070-eb2de4def815)

# 💬 To Reviewers
리뷰 부탁드립니다

2024-11-18 04:31 UTC, cbj0010 reviewed
리뷰 확인해주세용~!

2024-11-18 04:31 UTC, cbj0010 commented on src/test/java/com/wekids/backend/member/repository/MemberServiceTest.java
ServiceTest Service에 있어야 될거 같다고 생각합니다..!

2024-11-18 04:31 UTC, cbj0010 commented on src/main/java/com/wekids/backend/design/domain/Design.java
> +    @Column(name = "character", nullable = false)
`character` 이거 `` 써주셔야 sqld이랑 인식 다르게 한대요! 일부러 써주신거랍니다

2024-11-18 04:31 UTC, cbj0010 commented on src/main/java/com/wekids/backend/member/service/MemberServiceImpl.java
> +
parentId+"의 부모 정보를 찾을 수 없습니다." 요렇게 써주는게 저희 의도와 더 적할 할 거 같습니당!
요기 아래 있는 것들도요!

2024-11-18 04:54 UTC, jabin1221 commented on src/test/java/com/wekids/backend/member/repository/MemberServiceTest.java
앗.. 큰일날뻔했네 감사합니당

2024-11-18 04:55 UTC, jabin1221 commented on src/main/java/com/wekids/backend/design/domain/Design.java
> +    @Column(name = "character", nullable = false)
감사합니당 수정해볼게용

2024-11-18 04:57 UTC, dpdms529 requested changes

2024-11-18 04:57 UTC, dpdms529 commented on src/main/java/com/wekids/backend/account/repository/AccountRepository.java
> +    Design findDesignByAccountId(@Param("account_id") Long accountId);
Design 읽어오는건 DesignRepository에 만들어주세요

2024-11-18 04:57 UTC, dpdms529 commented on src/main/java/com/wekids/backend/member/dto/response/ChildResponse.java
> +    long childId;
여기만 primitive 타입 쓴 이유가 있나요?

2024-11-18 04:57 UTC, dpdms529 commented on src/main/java/com/wekids/backend/member/dto/response/ChildResponse.java
> +    ColorType color = null;
null넣으신 이유가 뭘까요?

2024-11-18 04:57 UTC, dpdms529 commented on src/main/java/com/wekids/backend/member/service/MemberServiceImpl.java
> +                .orElseThrow(() -> new WekidsException(ErrorCode.MEMBER_NOT_FOUND, "부모 정보를 찾을 수 없습니다."));
에러 메시지 수정해주세요

2024-11-18 04:57 UTC, dpdms529 commented on src/test/java/com/wekids/backend/support/fixture/ParentFixture.java
> +public class ParentFixture {
lombok builder 적용해서 만드시면 좋을것같습니다.

2024-11-18 04:57 UTC, dpdms529 commented on src/test/java/com/wekids/backend/support/fixture/DesignFixture.java
> +public class DesignFixture {
lombok builder 적용해서 만들면 좋을것같습니다.

2024-11-18 04:57 UTC, dpdms529 commented on src/test/java/com/wekids/backend/member/repository/MemberServiceTest.java
> +
가능하면 실패할 경우도 테스트해주셨으면 좋겠습니다.

2024-11-18 08:12 UTC, jabin1221 commented on src/main/java/com/wekids/backend/account/repository/AccountRepository.java
> +    Design findDesignByAccountId(@Param("account_id") Long accountId);
수정해보겠습니다 감사합니다

2024-11-19 05:50 UTC, khwoowoo requested changes

2024-11-19 05:50 UTC, khwoowoo commented on src/main/java/com/wekids/backend/design/repository/DesignRepository.java
> +    Design findByMemberId(Long memberId);
optional로 받으면 좋을 것 같습니다! 근데 designId가 memberId이니깐 그냥 정의하지 않아도 될 것 같은데 확인해보시면 좋을 것 같습니다!

2024-11-19 05:50 UTC, khwoowoo commented on src/main/java/com/wekids/backend/member/dto/response/ChildResponse.java
> +    public static ChildResponse from(Child child, Account account, Design design){
여러 개 입력 받으면 of라고 하는게 좋을 것 같습니다

아래 사이트는 참고해주세요!

https://velog.io/@coastby/SpringBoot-ResponseEntity.created

https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-%EC%83%9D%EC%84%B1%EC%9E%90-%EB%8C%80%EC%8B%A0-%EC%82%AC%EC%9A%A9%ED%95%98%EC%9E%90

2024-11-19 05:50 UTC, khwoowoo commented on src/main/java/com/wekids/backend/member/dto/response/ParentAccountResponse.java
> +    public static ParentAccountResponse from(ParentResponse parent, List<ChildResponse> children){
이것도요!

2024-11-19 05:50 UTC, khwoowoo commented on src/main/java/com/wekids/backend/member/dto/response/ParentResponse.java
> +    public static ParentResponse from(Parent parent, Account account, Design design){
이것도요!

2024-11-19 05:50 UTC, khwoowoo commented on src/main/java/com/wekids/backend/member/repository/MemberRepository.java
> +    Optional<Parent> findByIdAndMemberType(@Param("id") Long id);
그냥 id로 조회하는 것 같은데 이걸 만드신 이유가 있나요??

2024-11-19 05:50 UTC, khwoowoo commented on src/main/java/com/wekids/backend/member/service/MemberServiceImpl.java
> +
lombok 사용하고 있으니 @Autowired 사용 안 되고 될 것 같습니다!

2024-11-19 05:50 UTC, khwoowoo commented on src/main/java/com/wekids/backend/member/service/MemberServiceImpl.java
> +
조회하는건 메소드로 만드는게 가독성에 놓아보입니다! 그리고 디자인 조회는 optional로 받아서 없으면 예외 던지면 좋을 것 같네여!

2024-11-19 06:12 UTC, jabin1221 commented on src/main/java/com/wekids/backend/member/dto/response/ChildResponse.java
> +    public static ChildResponse from(Child child, Account account, Design design){
유익한 정보 알려주셔서 감사합니다!

2024-11-25 00:33 UTC, khwoowoo approved these changes

2024-11-25 01:03 UTC, dpdms529 commented on src/main/java/com/wekids/backend/account/repository/AccountRepository.java
> +import javax.swing.text.html.Option;
이거 쓰고 있는건가요?? 필요없으면 지워주세요.

2024-11-25 01:03 UTC, dpdms529 commented on src/main/java/com/wekids/backend/design/domain/Design.java
> +public class Design implements Serializable {
이제 IDClass 쓰는게 아니라 Serializable 필요 없을 것 같아요.

2024-11-25 01:03 UTC, dpdms529 commented on src/main/java/com/wekids/backend/design/domain/DesignId.java
이거 지워야돼요

2024-11-25 01:03 UTC, dpdms529 commented on src/main/java/com/wekids/backend/member/domain/Parent.java
> +@NoArgsConstructor
accessLevel Protected로 해주세요.

2024-11-25 01:03 UTC, dpdms529 commented on src/main/java/com/wekids/backend/member/repository/MemberRepository.java
> +    Optional<List<Child>> findChildrenByParentId(@Param("parentId") Long parentId);
List는 Optional 필요 없습니다.

2024-11-25 01:03 UTC, dpdms529 commented on src/main/java/com/wekids/backend/member/service/MemberServiceImpl.java
> +                .orElseThrow(() -> new WekidsException(ErrorCode.MEMBER_NOT_FOUND, "parentId가" + parentId + "인 부모 정보를 찾을 수 없습니다."));
findByXXX().orElseThrow() 는 다른데서도 많이 사용되기 때문에 메서드로 뽑아서 사용하면 좋을 것 같습니다.

2024-11-25 01:04 UTC, dpdms529 approved these changes

2024-11-25 01:05 UTC, merged