[FEAT] 자식 전 계좌 조회
woorifisa-projects-3rd/WeKids-BE pull request #44
Opened 2024-11-18 03:40 UTC by jabin1221

# 📄 Work Description
- 자식의 전 계좌 조회

# ⚙️ ISSUE
- closed #43 

# 📷 Screenshot
 - 포스트맨
![image](https://github.com/user-attachments/assets/d9cad81d-04f0-4fe0-9a36-f41e1ed7f13e)
 - 테스트 코드
![image](https://github.com/user-attachments/assets/a4703d1b-0440-46a1-94fb-81d9759db3db)

# 💬 To Reviewers
코드 리뷰 부탁드립니다

2024-11-18 05:12 UTC, dpdms529 commented on src/main/java/com/wekids/backend/account/dto/response/AccountChildListResponse.java
> +public class AccountChildListResponse {
AccountChildResponse 가 이 객체를 더 잘 설명할것같습니다.
안에 내용이 리스트는 아니니깐요.

2024-11-18 05:12 UTC, dpdms529 commented on src/main/java/com/wekids/backend/account/repository/AccountRepository.java
> +    Design findDesignByAccountId(@Param("account_id") Long accountId);
Desing객체는 DesignRepositoyr에서 읽어와야 맞는거같습니다.

2024-11-18 05:12 UTC, dpdms529 commented on src/main/java/com/wekids/backend/account/service/AccountService.java
> +    public List<AccountChildListResponse> findAccountChildList(long parentId);
findChildrenAccountList 는 어떨까요?
메서드명이 그 메서드가 뭐하는 메서드인지 잘 설명하도록 작성하면 좋을 것 같습니다.

2024-11-18 05:12 UTC, dpdms529 commented on src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
> +            Account childAccount = accountRepository.findByMember(child)
이거 select a.* from account a, member m  where a.memberId = m.id and m.id in :members ; 이런식으로 조회하면 한번에 가져올 수 있을거같은데 이거 jpa로 어떻게 해야하는지 함 찾아봐보세요

2024-11-18 05:12 UTC, dpdms529 commented on src/main/java/com/wekids/backend/member/repository/MemberRepository.java
> +    Optional<List<Child>> findChildrenByParentId(@Param("parentId") Long parentId);
List는 Optional 붙일 필요 없습니다.

2024-11-18 08:12 UTC, jabin1221 commented on src/main/java/com/wekids/backend/account/dto/response/AccountChildListResponse.java
> +public class AccountChildListResponse {
조언 감사합니다 수정해보겠습니다

2024-11-19 06:00 UTC, khwoowoo requested changes

2024-11-19 06:00 UTC, khwoowoo commented on src/main/java/com/wekids/backend/account/controller/AccountController.java
> +    AccountService accountService;
@RequiredArgsConstructor 이거 사용하는데 @Autowired를 사용 안 해도 좋을 것 같아용!  private final도 넣으면 좋을 것 가타용!

2024-11-19 06:00 UTC, khwoowoo commented on src/main/java/com/wekids/backend/account/repository/AccountRepository.java
> +    List<Account> findAccountsByParentId(@Param("parentId") Long parentId);
서브쿼리 보다는 조인이랑 페치조인하는게 더 좋을 것 같아요!

2024-11-19 06:00 UTC, khwoowoo commented on src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
> +        // 각 자녀의 계좌 정보 조회
주석은 빼도 좋을 것 같아요!

2024-11-25 02:47 UTC, khwoowoo approved these changes

2024-11-25 02:47 UTC, merged