Feat/#9 transfer
woorifisa-projects-3rd/WeKids-BE pull request #46
Opened 2024-11-18 16:27 UTC by cbj0010

# 📄 Work Description
- 이체 api 구현했슴둥

# ⚙️ ISSUE
- closed #9 

# 📷 Screenshot
### 이체 serviceTest
 ![image](https://github.com/user-attachments/assets/d8e9a079-5f36-439f-8c6a-9cd16d08d66b)
### 이체 controllerTest
![image](https://github.com/user-attachments/assets/4850a123-c697-4e66-90da-8595fe8fb28f)
### 이체 account repository test
![image](https://github.com/user-attachments/assets/aab28aeb-56c7-4fb6-bfeb-d710d6f2c656)
### postman
![image](https://github.com/user-attachments/assets/ebe68d33-6535-42e7-a662-fd1a9534ab8a)

### 실제 DB 변동 값
### 전
![image](https://github.com/user-attachments/assets/b2afcc16-7229-4a76-a611-290b44a5507e)
### 후
![image](https://github.com/user-attachments/assets/bb22cc6d-9bfb-450c-9624-cfaad2b96234)

# 💬 To Reviewers
리뷰어들에게 하고 싶은 말
리뷰 환영~

2024-11-20 05:17 UTC, cbj0010 commented
SENDER_AND_RECEIVER_SAME

2024-11-20 05:23 UTC, dpdms529 commented on src/main/java/com/wekids/backend/account/domain/Account.java
> +        this.balance = amount;
amount만큼 빼거나 더해야하는거 아닌가요?

2024-11-20 05:23 UTC, dpdms529 commented on src/main/java/com/wekids/backend/accountTransaction/controller/AccountTransactionController.java
> +    }
getTransactionDetails면 해당 거래 내역 읽어오는 API일텐데 왜 body가 없을까요?

2024-11-20 05:23 UTC, dpdms529 commented on src/main/java/com/wekids/backend/accountTransaction/controller/AccountTransactionController.java
> +        return ResponseEntity.noContent().build();
생성하는 API일 경우 HTTPS STATUS 코드 CREATED로 보내주세요

2024-11-20 05:23 UTC, dpdms529 commented on src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionService.java
> +    void saveTransaction(TransactionRequest transactionRequest);
거래를 저장한다기보다 이체를 위한 서비스 코드니깐 transfer라는 메서드명이 맞는 것 같습니다.
거래 저장말고도 많은 일을 동시에 처리하니깐용

2024-11-20 05:23 UTC, dpdms529 commented on src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImpl.java
> +
엔티티 생성 코드는 해당 엔티티에다가 만드는게 좋을 것 같습니다.

2024-11-20 05:23 UTC, dpdms529 commented on src/test/java/com/wekids/backend/account/repository/AccountRepositoryTest.java
> +        when(accountRepository.findAccountByAccountNumber("CHILD1234567890")).thenReturn(Optional.of(childAccount));
이게 왜 필요할까요? 
레포지토리 테스트는 가상으로 있다치고 테스트할게 없어서 보통 junit으로 테스트합니다.
Mock 테스트는 서비스코드에 대해서 테스트하기 위해 있는거라서 굳이 안해도될거같아요.

2024-11-20 07:24 UTC, khwoowoo requested changes

2024-11-20 07:24 UTC, khwoowoo commented on src/main/java/com/wekids/backend/account/domain/Account.java
> +        this.balance = amount;
코드 리뷰하면서 봤는데 서비스단에서 하는 것 같습니다!

2024-11-20 07:24 UTC, khwoowoo commented on src/main/java/com/wekids/backend/accountTransaction/controller/AccountTransactionController.java
> +        return ResponseEntity.noContent().build();
왜 값을 가져와서 값을 응답으로 안 주나용?? 이유가 있나용?

2024-11-20 07:24 UTC, khwoowoo commented on src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImpl.java
> +        log.info(String.valueOf(childAccount));
로그를 작성할거면 조금 더 구체적으로 작성하면 좋을 것 같아요! 나중에 문제생겼을 때 확인할 수 있게! 그리고 나중에 여유되시면 파일로 저장하는 코드도 작성하면 좋을 것 같네요!

2024-11-20 07:24 UTC, khwoowoo commented on src/main/java/com/wekids/backend/accountTransaction/dto/request/TransactionRequest.java
> +}
bean vailidation 넣으면 좋을 것 같습니당!

2024-11-20 07:24 UTC, khwoowoo commented on src/main/java/com/wekids/backend/accountTransaction/controller/AccountTransactionController.java
> +        return ResponseEntity.noContent().build();
그리고 이게 계좌 내역 조회하는 코드라면 서비스단이랑 레파지토리단이랑 코드가 너무 헷갈리는 것 같네용. showTransaction 같은 이름으로 하는게 좋아보입니당

2024-11-20 11:25 UTC, dpdms529 requested changes

2024-11-20 11:25 UTC, dpdms529 commented on src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImpl.java
> +    public void saveTransaction(TransactionRequest transactionRequest) {
저희 서비스에 저장하기 전에 먼저 BaaS에 이체 API 보내서 성공해야 밑에 로직이 수행되는게 맞는것 같습니다.
BaaS에 이체 API 호출하는 코드 구현해주세요.

2024-11-25 03:43 UTC, khwoowoo approved these changes

2024-11-25 03:44 UTC, dpdms529 approved these changes

2024-11-25 03:44 UTC, merged